name: Check codebase

on:
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        python-version: [ 3.11 ]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pyenv
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
          key: py-${{ matrix.python-version }}-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}

      - name: Install deps
        run: bin/install.sh

      - name: Test codebase
        run: bin/test.sh
